lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # token TTL in seconds, defaults to 1 hour

    token_extractors:
        # Default header auth, can be useful to allow for other auth types (for example /api)
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization

        # Make sure this is enabled
        cookie:
            enabled: true
            name: BEARER

                
