# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/5.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
       # - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
       # - Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken
    email:
        digits: 6
        enabled: true
        sender_email: no-reply@example.com
        sender_name: John Doe  # Optional