security:

    password_hashers:
        App\Entity\User: 'auto'

    enable_authenticator_manager: true
   
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false                 
        login:
            lazy: true
            pattern: ^/api/login
            stateless: false
        
            provider: app_user_provider

            json_login:
                check_path: login 
                # success_handler: App\Security\AuthenticationSuccessHandler
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure  
                
           # two_factor:
            #    prepare_on_login: true
                # prepare_on_access_denied: true   
                # success_handler: App\Security\TwoFactorAuthenticationSuccessHandler  
                # failure_handler: App\Security\TwoFactorAuthenticationFailureHandler 
                # authentication_required_handler:  App\Security\TwoFactorAuthenticationRequiredHandler
                # check_path: 2fa_login_check  # The route name you have used in the routes.yaml
                # auth_code_parameter_name: authCode     
             
        main:
            pattern: ^/api/logout
            logout:
                path: api_logout 
        
        api:
            pattern: ^/api
            jwt: ~ 
            stateless: false            


    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS } # Allows to login

        - { path: ^/api/ogin/2fa_check, role: PUBLIC_ACCESS }

        - { path: ^/docs, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI

        - { path: ^/api, roles: PUBLIC_ACCESS }
 
           
        # /api/2fa_check

        
